- README.md
After the refactor the images weren't displaying correctly
> update readme.md with correct image links

- README.md
Fixes https://github.com/devcontainers/spec/issues/42.
> Add mention of images

- proposals/devcontainer-features.md
> fix spelling mistakes

- README.md
Using the CI repo and content in https://code.visualstudio.com/updates/v1_68#_dev-container-in-ci as a reference.
> Add CI info

- contributing.md
Now that we've enabled Discussions in this repo, let's update the contributing info so that users are aware.
> Update contributing.md with Discussions

- proposals/devcontainer-features.md
Reference - https://github.com/devcontainers/cli/pull/94#discussion_r934699737
> Proposal Update: Add note and ex. for `latest` version

- proposals/devcontainer-features-distribution.md
- proposals/devcontainer-features.md
There was some missing info and typos I corrected.  I also linked out to the new feature-template and features repositories. //cc @bamurtaugh
> Add clarifications, fix typos for Dev Container Features proposal

- proposals/devcontainer-features-distribution.md
- proposals/devcontainer-features.md
Fix small typos found while working on https://github.com/devcontainers/devcontainers.github.io/pull/26.
> Fix small typos

- proposals/parallel-lifecycle-script-execution.md
Coming out of discussions on https://github.com/devcontainers/spec/issues/83.
Propose supporting parallel lifecycle script execution when scripts are provided as objects.
> Parallel lifecycle script execution proposal

- proposals/devcontainer-templates-distribution.md
- proposals/devcontainer-templates.md
The proposal is an idea of how to author and distribute Templates. This follows a very similar mechanism as of dev container [Features](https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md)
> Dev container Templates & distribution

- docs/specs/supporting-tools.md
Updates based on latest extension name.
> Update based on latest naming

- docs/specs/supporting-tools.md
Add a section on Visual Studio.
> Update supporting-tools.md with VS

- docs/specs/devcontainer-reference.md
- schemas/devContainer.base.schema.json
Reflect the support for the object form of lifecycle commands.
> Update spec and schema for lifecycle command changes

- docs/specs/devcontainer-features.md
closes https://github.com/devcontainers/cli/issues/269
> `installsAfter` clarification

- docs/specs/supporting-tools.md
Site update is https://github.com/devcontainers/devcontainers.github.io/pull/100
> Add limitations, new supporting tools

- docs/specs/devcontainer-features.md
closes https://github.com/devcontainers/spec/issues/160
> typo: `installAfter` -> `installsAfter`

- proposals/features-legacyIds-deprecated-properties.md
Spec Issue - https://github.com/devcontainers/spec/issues/146
> Features : Add support for renaming and deprecating

- schemas/devContainerFeature.schema.json
Spec PR - https://github.com/devcontainers/spec/pull/163
Spec issue - https://github.com/devcontainers/spec/issues/146
CLI PR - https://github.com/devcontainers/cli/pull/346
> Feature Schema Update - Adds 'deprecated'

- docs/specs/supporting-tools.md
Follow up to https://github.com/devcontainers/devcontainers.github.io/pull/105.
> Add docs for `codespaces.openFiles`, part 2

- docs/specs/devcontainer-features.md
- schemas/devContainerFeature.schema.json
Spec PR - https://github.com/devcontainers/spec/pull/163
Spec issue - https://github.com/devcontainers/spec/issues/146
CLI PR
- https://github.com/devcontainers/cli/pull/335
> Features: Adds a new 'legacyIds' property

- schemas/devContainer.base.schema.json
Reported in https://github.com/devcontainers/spec/issues/175
> Update devcontainer.json schema - Adds 'overrideFeatureInstallOrder'

- schemas/devContainer.base.schema.json
> Add deprecation messages to legacy features

- proposals/declarative-secrets.md
ref: https://github.com/devcontainers/spec/issues/198
> Add a proposal for declarative secrets

- docs/specs/devcontainer-features.md
- docs/specs/devcontainer-reference.md
ref: https://github.com/devcontainers/spec/issues/60, https://github.com/devcontainers/spec/issues/181
Adds missing lifecycle hooks properties to the overall Features spec.
> Add lifecycle hooks to Features spec

- proposals/feature-dependencies.md
Proposal for Feature dependencies (if accepted, superseding [Composite Features](https://github.com/devcontainers/spec/pull/208).)
ref: https://github.com/devcontainers/spec/issues/109
reference implementation: https://github.com/devcontainers/cli/pull/530
> [Proposal] Feature `dependsOn`

- docs/specs/devcontainer-reference.md
ref: https://github.com/devcontainers/devcontainers.github.io/pull/229
> Update spec on location of nested dev containers

- schemas/devContainer.base.schema.json
> fix: allow `$schema` property in `devcontainer.json`

- proposals/devcontainer-lockfile.md
https://github.com/devcontainers/spec/issues/236
https://github.com/devcontainers/cli/issues/564
> Add dependsOn to lockfile

- contributing.md
> Fix typo formated -> formatted

- docs/specs/devcontainer-features-distribution.md
- docs/specs/devcontainer-features.md
ref https://github.com/devcontainers/spec/issues/109
Synthesizes the Feature Dependencies proposal (https://github.com/devcontainers/spec/pull/234) into the specification
> Add Feature Dependencies changes to main spec

- schemas/devContainer.base.schema.json
microsoft/vscode-remote-release#8994
> Update deprecation messages

- schemas/devContainerFeature.schema.json
Closes: https://github.com/devcontainers/spec/issues/356
> Fix schema syntax error

- schemas/devContainerFeature.schema.json
fixes: https://github.com/devcontainers/spec/issues/204
> fix: add missing "keywords" property to feature schema

- docs/specs/supporting-tools.md
See related vscode devcontainer schema PR: https://github.com/microsoft/vscode/pull/223083
Documenting a new codespaces setting.
> Document `codespaces.disableAutomaticConfiguration`

- docs/specs/devcontainer-features.md
> Fix fat-finger incidents
