devcontainers/spec

contributing.md

Document how users may contribute to `customizations`, as we discussed in https://github.com/devcontainers/spec/issues/1.

Add `customizations`

---

docs/specs/devcontainer-reference.md
docs/specs/devcontainerjson-reference.md
docs/specs/supporting-tools.md

This is an initial version of the specification.
cc @Chuxel, @chrmarti, @joshspicer

Initial version of the spec.

---

proposals/devcontainer-features.md

After the beta functionality of features included today and with the feedback we have received so far, here is a proposal to define Features and how the work, get community feedback and create a formalized spec that can be implemented.

Proposal for Features functionality and spec.

---

docs/specs/devcontainer-reference.md
docs/specs/supporting-tools.md

Fixes and additions to the spec.

---

docs/specs/devcontainer-reference.md

I realized after the fact that it is not obvious when UID/GID syncing should be happening by just reading the devcontainer metadata reference.
Added a clarification.  @bamurtaugh - FYI, adds one more link.

Add description about UID/GID sync'ing

---

proposals/devcontainer-features.md

@Chuxel, @chrmarti, @alexdima, @jkeech, @joshspicer, @samruddhikhandale 
closes https://github.com/devcontainers/spec/issues/43

Updating features proposal after latest discussions.

---

proposals/devcontainer-features-distribution.md
proposals/devcontainer-features.md

relevant to: https://github.com/devcontainers/spec/issues/7
- Proposes OCI artifact registries as storage medium for features assets
- Clarifies packaging and distribution steps
- Clarifies several parts of the existing, general 'features' proposal 
For historical discussion, see https://github.com/devcontainers/spec/pull/40

[Proposal] 'Features' Distribution Specification

---

schemas/devContainer.base.schema.json
schemas/devContainer.schema.json

Implementing devcontainer schema proposal https://github.com/devcontainers/spec/issues/14#issuecomment-1185373811

add dev container schema

---

proposals/devcontainer-features-distribution.md

This is the media type the spiked GitHub action implements, and how https://github.com/devcontainers/features/pkgs/container/features is published today.

typo with devcontainer-collection oci media type

---

proposals/devcontainer-features.md

The feature IDs provided in `overrideFeatureInstallOrder` must be referenced without the semantic version.

Spec update: Feature id referencing with overrideFeatureInstallOrder

---

proposals/devcontainer-features.md

This PR calls out the fact that `install.sh` for Features should execute as root and clarifies how different shells should be used.
This addition is as a result of conversations around #91 and #92

Add more information on how install.sh should be invoked, used

---

proposals/image-metadata.md

Continuing from https://github.com/devcontainers/spec/issues/18.

Image Metadata Proposal

---

docs/specs/supporting-tools.md

`waitFor` and `workspaceFolder` are now supported in Codespaces.

Now supported in codespaces

---

docs/specs/devcontainer-features-distribution.md
proposals/devcontainer-templates-distribution.md
proposals/devcontainer-templates.md

Backports https://github.com/devcontainers/devcontainers.github.io/pull/66 to the spec repo.
@bamurtaugh LMK if it would be easier to merge this into https://github.com/devcontainers/spec/pull/128 instead.

Backport updates related to https://github.com/devcontainers/devcontainers.github.io/pull/66 to the spec

---

proposals/features-contribute-lifecycle-scripts.md

ref: https://github.com/devcontainers/spec/issues/60, https://github.com/devcontainers/spec/issues/181

Add proposal for features contributing lifecycle scripts

---

schemas/devContainer.base.schema.json
schemas/devContainerFeature.schema.json

With CLI v0.32.0 and https://github.com/devcontainers/cli/pull/390, devcontainer-feature.json now support lifecycle hooks.
Spec proposal:
https://github.com/devcontainers/spec/blob/b1d19a5375f667a1bb91e86311bc37c36312996b/proposals/features-contribute-lifecycle-scripts.md

[schema] Add lifecycle hooks to devContainerFeature

---

proposals/features-library.md

ref: https://github.com/devcontainers/spec/issues/129

[proposal] Sharing code between Dev Container Features

---

proposals/secrets-support.md

Formal proposal based on https://github.com/devcontainers/spec/issues/219
This proposal do not change the devcontainers spec itself, rather it is a proposal on the implementation of secrets support in supporting tools such as the devcontainers CLI (which could serve as a potential reference implementation)

Proposal: First class secrets support in dev containers implementations

---

contributing.md
docs/specs/devcontainerjson-reference.md

Hi,
i have noticed that the link to the schema which is referenced in [`contributing.md`](https://github.com/devcontainers/spec/blob/main/contributing.md?plain=1#L17) and [`devcontainerjson-reference.md`](https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainerjson-reference.md?plain=1#L164) is broken. It links to a `devContainer.schema.src.json` file that no longer exists in the vscode repo (removed in this [PR](https://github.com/microsoft/vscode/pull/169857)).
I have adjusted the docs to link to the [`devContainer.base.schema.json`](https://github.com/devcontainers/spec/blob/main/schemas/devContainer.base.schema.json) which is found in this repo.
I hope this is correct. If not, sorry for any inconvenience.

[Docs] fixes broken link 

---

docs/specs/devcontainer-reference.md

Found this issue while browsing the spec. Without proper styling, it is unable to be displayed in the browser.
This is what it currently looks like:

Fix documentation markdown styling

---

proposals/devcontainer-lockfile.md

https://github.com/devcontainers/spec/issues/236

Record identifiers in lowercase

---

docs/specs/devcontainer-features-distribution.md
docs/specs/devcontainer-features.md

related https://github.com/devcontainers/spec/pull/278, https://github.com/devcontainers/cli/pull/293

Notes on Feature identifier casing

---

schemas/devContainer.base.schema.json
schemas/devContainerFeature.schema.json

**Description**:
The `source` attribute could be omitted for the `mount` command. In this case, Docker uses anonymous volumes. We update the devcontainer CLI to support such a case, and we need to update schemas to set the `source` property as optional.
_Changelog_:
- The `source` property was removed from `required` array;
**Related changes**:
- https://github.com/devcontainers/cli/pull/537

Set `source` property as not required for `Mount`

---

schemas/devContainer.base.schema.json

Updates schema to eliminate the invalid/confusing linter errors with [declarative secrets](https://github.com/devcontainers/spec/blob/main/proposals/declarative-secrets.md).
This file is [referenced by VS Code](https://github.com/microsoft/vscode/blob/main/extensions/configuration-editing/package.json#L143).
Related: https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/specifying-recommended-secrets-for-a-repository#specifying-recommended-secrets-in-the-dev-container-configuration
https://github.com/devcontainers/spec/assets/23246594/dcf7b282-57d3-421e-bc21-5fc22e92d193

Add declarative secrets schema

---

docs/specs/devcontainer-templates-distribution.md

The push and pull examples do not work with the current cli.  It looks like the `--manifest-config` option was renamed to `--config` some time ago.

update templates-distribution to have working oras examples

---

schemas/devContainerFeature.schema.json

relevant: https://github.com/devcontainers/action/issues/205
See https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-features.md#the-dependson-property for more information on the property

add `dependsOn` to devContainerFeature.schema.json

---

proposals/build-cli-options.md
proposals/build-options.md

Added a simple proposal for the spec change in https://github.com/devcontainers/spec/pull/324

Added build cli options proposal

---

docs/specs/secrets-support.md

Fix a minor formatting issue in `docs/specs/secrets-support.md` to display json sample correctly

Fix formatting

---

docs/specs/devcontainer-templates.md

Related contexts: 
- https://github.com/microsoft/vscode-remote-release/issues/10095#issuecomment-2260982054 
- https://github.com/devcontainers/templates/issues/274
Reference implementation change: 
- https://github.com/devcontainers/cli/pull/868
Related changes:
- https://github.com/devcontainers/cli/pull/865
- https://github.com/devcontainers/cli/pull/866

Proposal: Template `optionalPaths` property

---

docs/specs/devcontainer-features.md

The init process used by `docker run --init` is `krallin/tini`, not `RKrahl/tiny-init`.

Fix description of `init` attribute in `devcontainer-features.json`.

---

docs/specs/devcontainer-features.md

Steps **(1)** and **(2)** have 3 pounds, but **(3)** has 4:
* [(1) Build a dependency graph](https://github.com/devcontainers/spec/blob/9fb374c7f29b4e3aaf55e7df69ed7514d6189dcd/docs/specs/devcontainer-features.md?plain=1#L385)
* [(2) Assigning round priority](https://github.com/devcontainers/spec/blob/9fb374c7f29b4e3aaf55e7df69ed7514d6189dcd/docs/specs/devcontainer-features.md?plain=1#L393)

Fix incorrect heading size
